pki:
  ca:                   /etc/nebula/ca.crt
  cert:                 /etc/nebula/host.crt
  key:                  /etc/nebula/host.key

lighthouse:
  interval:             60

listen:
  host:                 0.0.0.0
  port:                 4242
  batch:                128
  # read_buffer:        10485760
  # write_buffer:       10485760

punchy:
  punch:                true
  respond:              true
  delay:                1s
  punch_back:           true

tun:
  disabled:             false
  dev:                  nebula1
  drop_local_broadcast: false
  drop_multicast:       false
  tx_queue:             5000
  mtu:                  1440
  routes:
  unsafe_routes:

logging:
  level:                info
  format:               text

firewall:
  conntrack:
    tcp_timeout:        12m
    udp_timeout:        3m
    default_timeout:    10m

  outbound:
    # Allow all outbound traffic from this node
    - port:             any
      proto:            any
      host:             any

  inbound:
    # Allow icmp between any nebula hosts
    - port:             any
      proto:            icmp
      host:             any

    # Allow Bob Joe all access
    - port:             any
      proto:            any
      host:             any
      group:            bobjoe
