static_host_map:
  "10.0.0.1":  ["example.com:4242"]
  "10.0.0.2":  ["312.132.123.132:4242"]
  "10.0.0.3":  ["453.234.432.243:4242"]

lighthouse:
  hosts:
    - "10.0.0.1"
    - "10.0.0.2"
    - "10.0.0.3"
  am_lighthouse: false

relay:
  relays:
   - 10.0.0.1
   - 10.0.0.2
   - 10.0.0.3
  am_relay:      false
  use_relays:    true
